### ISSUE TITLE
Upload reference sequence for samples 

### ISSUE THREAD

**Issue by EdGreen21** [ssciwr/circuit_seq#1]
In our testing the sequence assembly pipelines work much better when a reference sequence (i.e. "best guess") is provided as input.  I would be great if when specifying a new sample, a user could also upload a reference sequence. Generally these are in fasta (*.fa) format, a very simple format where there is a header line (starting with ">"), header information, a newline, and then DNA.  Example would be:

>example sequence name
atgctgatcgtaggcttaggatgcgaaaaagccca

**Comment by LArnoldt** [comment]
It would be good if the upload of reference sequences is non-mandatory. 

As commented in the #5 issue: These reference sequences need to be able to be assigned to a sample. As suggested there it would probably enough if the fasta files are renamed to the sample names.
