### ISSUE TITLE
add email activation step for sign-ups

### ISSUE THREAD

**Issue by lkeegan** [ssciwr/circuit_seq#16]
When a user signs up, they should get an email with an activation link to confirm they entered their own email address.

Their account shouldn't be active until they have clicked on this link.

This may require us to add an STMP server to the VM, unless we can get an email account e.g. from embl or dkfz to use for this? (same goes for emailing the results to the users)

**Comment by EdGreen21** [comment]
I will request a DKFZ email account as a backup. 

I imagine adding an SMTP email server in Docker is fairly easy, but getting the port forwarding permissions might need a bit of digging/discussion with ITCF.

**Comment by EdGreen21** [comment]
requested `circuitseq@dkfz-heidelberg.de`

**Comment by EdGreen21** [comment]
one time login details for `circuitseq@dkfz-heidelberg.de` attached - @lkeegan could you work with these? You may wish to set the password and keep it in an encrypted file etc (not sure what best practice is)
[circuits20221107111525.pdf](https://github.com/ssciwr/circuit_seq/files/9953070/circuits20221107111525.pdf)

**Comment by lkeegan** [comment]
@EdGreen21 thanks! I was able to login and change the password

**Comment by EdGreen21** [comment]
@EdGreen21 to check back with ITCF that this is allowable use of DKFZ email

**Comment by EdGreen21** [comment]
@lkeegan the person I would need to contact at DKFZ who manages usernames is [a.dietz@dkfz.de](mailto:a.dietz@dkfz.de). 

Can you describe the problem you are having with the email account in a little more detail? My understanding was that you could log in to [DKFZ webmail](http://webmail.dkfz.de/) using the account, but can't get programatic access to work and think it might be blocked. 

 Is there anything we (likely @larnoldt) can test here that would help?

**Comment by lkeegan** [comment]
That's right, webmail works, but I try to use smtp I can't connect to the server, e.g.

`ping dkfzmh04.ad.dkfz-heidelberg.de`

gives `ping: dkfzmh04.ad.dkfz-heidelberg.de: Name or service not known`

@LArnoldt would you mind trying to ping it from inside the dkfz network?
