### ISSUE TITLE
determine week number based on current date

### ISSUE THREAD

**Issue by lkeegan** [ssciwr/circuit_seq#17]
- for now it is just hard-coded to 1
- instead it should be calculated from the current date
- maybe define 1 to be the week of the first requested sample in the database?

**Comment by EdGreen21** [comment]
ideally prepend with the last 2 digits of year. 

Most languages have a dedicated function for weeks - simplest would be to use these?

**Comment by lkeegan** [comment]
Sounds good to me - so the primary key for e.g. the first sample of this week would be `22_44_A1`?

**Comment by EdGreen21** [comment]
correct
