### ISSUE TITLE
domain name

### ISSUE THREAD

**Issue by lkeegan** [ssciwr/circuit_seq#18]
For user-friendliness (and to be able to enable https) it would be good to have a domain name for the website:

- maybe a dkfz or embl subdomain would be best?
- or just register an external one?
- alternatively I could ask for an IWR subdomain e.g. circuit-seq.iwr.uni-heidelberg.de

**Comment by EdGreen21** [comment]
We've got funding for a 3 month trial, if at the end of that period we feel we can successfully run the service then we'd look to see if the institutes would want to further fund Circuit-SEQ. The funding institute would likely want to host  the server in such a case.

So answer is: if getting the IWR subdomain is simple please host here, mid term the solution would be to ensure maximum portability using Docker to allow transfer to dkfz/embl/uni as appropriate

**Comment by EdGreen21** [comment]
Example of a DKFZ hosted website run by the Boutros group: [http://genomecrispr.dkfz.de/](http://genomecrispr.dkfz.de/)

**Comment by EdGreen21** [comment]
For a website to be hosted run by DKFZ, it would need to meet the DKFZ corporate design rules and fit with their Content Management System. Content would also need to be discussed with [Roman Jowanowitsch](mailto:r.jowanowitsch@dkfz.de).

Ideally prioritise development time on core functionality, can revisit corporate design theme issues later in project - IWR may also have rules

**Comment by lkeegan** [comment]
Ok I'll ask the IWR for a subdomain to use for now then.

The website is currently hosted on a heicloud VM at this IP address: http://129.206.7.129/ for (up to) a year, and it should be straightfoward to transfer the docker setup elsewhere for longer term hosting at any point. (integration with a CMS would require additional work though)
