### ISSUE TITLE
Allowable email domains (living list)

### ISSUE THREAD

**Issue by EdGreen21** [ssciwr/circuit_seq#2]
Àllowable email domains to include:
`@dkfz.de` (and variants e.g. `@dkfz-heidelberg.de`)
`@uni-heidelbeg.de` (this is the top level, so this whould also include for example `@medma.uni-heidelbeg.de` and `@zmbh.uni-heidelberg.de`)
`@embl.de`

**Comment by lkeegan** [comment]
Currently done on the frontend: users can only sign up with emails that match this regexp:
https://github.com/ssciwr/circuit_seq/blob/1fbfbd16dff2efc1a6604aa2c34d18fe39177c92/frontend/src/views/LoginView.vue#L14

Also need to do this on the backend
