### ISSUE TITLE
Acceptable sample name logic clarification 

### ISSUE THREAD

**Issue by EdGreen21** [ssciwr/circuit_seq#25]
It's not entirely clear from the submission from that the sample name MUST include underscores and exclude special characters - the "Request Sample" button remains greyed out, but a user might be confused. 

Ideally write the sample name rules (or link to them), and/or have a dynamic part of the web page that informs the user when an ineligible name is entered

**Comment by lkeegan** [comment]
I agree - this information is displayed but only if you hover the mouse over the field or submit button, I'll make this always visible for invalid fields
