### ISSUE TITLE
serving on localhost:5000 not working 

### ISSUE THREAD

**Issue by EdGreen21** [ssciwr/circuit_seq#31]
Windows system running Docker isn't serving on localhost:5000 as commited here 4a600f68c3b994a6ab6855c68e0abbc05f9dccd3 - not sure if this is actively in development or not

**Comment by lkeegan** [comment]
Running `docker-compose up --build` should serve:

- the user-facing website at http://localhost/
- the server REST API at http://localhost:5000
  - this should display a `Not Found` page if you go to this url in a browser
  - but e.g. http://localhost:5000/remaining should return the remaining samples this week 
  - and http://localhost:5000/admin/allsamples should return an authorization error

If this isn't the case would you mind pasting the output of running the above docker-compose command here? (I haven't tried using this on windows)

**Comment by EdGreen21** [comment]
thanks for the clarification, this works
