### ISSUE TITLE
Reference sequence (optional) - file format control / reading common sequence files

### ISSUE THREAD

**Issue by EdGreen21** [ssciwr/circuit_seq#41]
Currently selecting a non-compatible file as a reference sequence throws a silent error.

File format for reference sequence can be controlled in the file selection box. In the simplest case we should allow:
-  *.txt (comma or tab sep)
-  *.fa
- *.fasta

There are 2 very detailed formats for storing sequence information that could also be considered: 
- genbank (*.gb or *.gbk) 
- snapgene (*.dna). 

If we wish to read these (not a priority, but would save users work) the simplest solution is likely to be biopython's [SeqIO module ](https://biopython.org/wiki/SeqIO). SeqIO also likely to better handle errors in dodgy text files uploaded by users as it's a very established platform.

**Comment by lkeegan** [comment]
We're already using SeqIO to read the uploaded fasta files, so it should be straightforward to support more formats (either by guessing the format based on the filename extension, or just by trying to parse the uploaded file as each format until one works)

Currently an invalid file is ignored but the sample is still requested, I guess it would be better for the sample request to fail with an error message if a reference sequence is provided that can't be parsed?

**Comment by EdGreen21** [comment]
"Currently an invalid file is ignored but the sample is still requested" >> I would suggest a notification that the reference file couldn't be parsed

Please enable *.dna and *.gb/*/gbk in addition to *.txt *.fa and *.fasta, but for the references always return a *.fa in the zip file

**Comment by EdGreen21** [comment]
@LArnoldt

**Comment by EdGreen21** [comment]
I really like @lkeegan's implementation on *.fasta or *.fa files  - these are often not quality controlled with people naming multifasta containing multiple sequences as *.fa.

Nice that you've already coded SeqIO to only load the first sequence

**Comment by EdGreen21** [comment]
[Example_snapgene_file.zip](https://github.com/ssciwr/circuit_seq/files/10044410/Example_snapgene_file.zip)

Here is a *.dna file as an example. Upload works, though the name display isn't quite right. Probably fine as is - will check when passing files to downstream analysis

**Comment by lkeegan** [comment]
Thanks - I tried reading that file with seqio and [snapgene-reader](https://pypi.org/project/snapgene-reader/), they both gave `id='<unknown id>'`, but snapgene-reader also provided a `notes` section:
```
'ConfirmedExperimentally': '0',
 'Created': {'#text': '2021.5.12', '@UTC': '20:20:1'},
 'CustomMapLabel': 'Tet-pLKO-puro',
 'Description': '3rd generation lentiviral plasmid for inducible expression of '
                'shRNA; puromycin selection. See manual for detailed '
                'protocols. No further technical support is available from the '
                'depositing laboratory..',
 'LastModified': {'#text': '2021.5.12', '@UTC': '20:20:1'},
 'References': {'Reference': {'@authors': 'Wiederschain D, Wee S, Chen L, Loo '
                                          'A, Yang G, Huang A, Chen Y, '
                                          'Caponigro G, Yao YM, Lengauer C, '
                                          'Sellers WR, Benson JD',
                              '@journal': 'Cell Cycle. 2009 Feb 1. '
                                          '8(3):498-504.',
                              '@pubMedID': '19177017',
                              '@title': 'Single-vector inducible lentiviral '
                                        'RNAi system for oncology target '
                                        'validation.'}},
 'SequenceClass': 'UNA',
 'TransformedInto': 'unspecified',
 'Type': 'Synthetic',
 'UUID': 'fa01f25f-d83f-49dc-809b-e64d29612a27',
 'UseCustomMapLabel': '1'
```
Let me know if there's a field above that would make sense to use instead of the `<unknown id>`

**Comment by LArnoldt** [comment]
` 'Tet-pLKO-puro' ` ('CustomMapLabel') would fit here instead of <unknown id>.
