### ISSUE TITLE
add endpoint to upload analysis results

### ISSUE THREAD

**Issue by lkeegan** [ssciwr/circuit_seq#43]
- should be possible to do this from the admin web-page as well as via a rest api call
- likely format is two files
  - small zipfile of results (~1mb? zipped per sample)
  - large zipfile of full results (~300mb zipped per sample)

**Comment by LArnoldt** [comment]
Hey, I have added two "sample zipfiles" to this message.

They assume that the samples "ZIP_TEST_pMC_Final_Kan", "ZIP_TEST_pCW571" and "ZIP_TEST_pDONR_amilCP" have been submitted. 

"results_email.zip" contains all the files, which should be emailed to the users. 
"results_full.zip" contains just everything, which should be stored on the server for download (including the files, which are sent to the users).
[results_full.zip](https://github.com/ssciwr/circuit_seq/files/10014641/results_full.zip)
[results_email.zip](https://github.com/ssciwr/circuit_seq/files/10014642/results_email.zip)

Is it more covenient for you if results_email.zip is uploaded separately or could these files, which are sent to the users, also just be stored in results_full.zip?

**Comment by lkeegan** [comment]
Thanks! From my side either way is fine, but I'd probably go for the simpler option of just uploading a single `results_full.zip` file.

**Comment by lkeegan** [comment]
Thinking some more about this I think uploading a single huge zip file is not a good long-term solution - will likely run into various issues as you scale up the service (e.g. upload fails after 59.9/60gb uploaded, script appearing to hang if upload takes a long time, freezing/overloading the server/website while this long operation is being dealt with, etc)

What would I think be a good API would be to upload a single zip file with all the data for a single sample - then there should be no issues scaling up to processing many more samples, it's the same operation being done more times rather than a single operation getting bigger. This upload step could be done from a python script in a loop or even as each sample is processed.

@LArnoldt would that work for you? If so I would implement this & add a notebook with some python API examples of how to use it. Also happy to have a quick call to discuss if that would be helpful.

**Comment by LArnoldt** [comment]
Hey, sorry for reacting so slowly. I think, your solutions sounds very reasonable. & We should do it like this. API Examples also look very good. I will test them out today & do some experiments.

**Comment by lkeegan** [comment]
@LArnoldt I've removed the test user/admin accounts from the website - you should be able to sign up using your real email address now. If you can let me know once you have an account then I'll make it into an admin one so you can generate an API key. (The generated API keys should now remain valid for 6 months)

**Comment by LArnoldt** [comment]
Just trid to sign up. However, it does not given my a "success message" or sth. similar?

**Comment by lkeegan** [comment]
Sorry about that - it should give you a success / failure message.
It could be that I updated the server just as you were signing up (I did this about 10 mins ago and I don't see your signup attempt in the logs) - would you mind trying it again?

**Comment by LArnoldt** [comment]
Done. Account should be now ready for activation by you.

**Comment by lkeegan** [comment]
Great! You should get an email with a link for activating the account. I'll make it an admin account now

**Comment by lkeegan** [comment]
OK if you login again you should see the admin page.

**Comment by LArnoldt** [comment]
Great. I will do a complete test run of the plattform tomorrow afternoon.

@EdGreen21 Would probably good if you get an admin account as well.

**Comment by LArnoldt** [comment]
Have tested the API & did the integration with out pipeline: Works great! Thank you very much @lkeegan !

Some minor points:

- Ed & I discussed the running options again & would like to not provide any at the moment. Could the running options not be displayed for the users if the number of running options is below 2?

- FYI: I am currently trying to resolve an issue concerning the API with the IT of the cluster we are running the analysis on. Since the REST protocol works perfectly locally I guess this is mainly a cluster-side blockade. If the cluster IT does not allow us to unblock these sites I will refactor the code so it does the uploading & downloading on the local machine.

- Concerning the REST API: Is it intended that the HTTPS server is listerning at port 8080, which would normally be used as an alternative non-SSL port?

**Comment by lkeegan** [comment]
> Have tested the API & did the integration with out pipeline: Works great! Thank you very much @lkeegan !
> 

Great! Did you also receive an email with the results?
Looking at the logs I guess maybe you didn't, as the filenames inside the zip file didn't match the expected filenames so it didn't extract the fasta/gbk files to send to the user.

> Some minor points:
> 
> * Ed & I discussed the running options again & would like to not provide any at the moment. Could the running options not be displayed for the users if the number of running options is below 2?

Sure - in this case should it should always use the first running option from the list?

> * FYI: I am currently trying to resolve an issue concerning the API with the IT of the cluster we are running the analysis on. Since the REST protocol works perfectly locally I guess this is mainly a cluster-side blockade. If the cluster IT does not allow us to unblock these sites I will refactor the code so it does the uploading & downloading on the local machine.
> * Concerning the REST API: Is it intended that the HTTPS server is listerning at port 8080, which would normally be used as an alternative non-SSL port?

I used 8080 for no reason except that it wasn't blocked by the uni firewall, while the default 5000 was for some reason.

Some possible fixes:

- (quickest & easiest solution) change the REST API port from 8080 to one that isn't blocked by your cluster (or the uni firewall)
- (more work but probably a better solution) change the deployment so the REST API is served on the same 443 port as the website
  - API calls would then have an /api prefix and be routed by nginx internally to the backend
  - this is issue #40

**Comment by LArnoldt** [comment]
> Great! Did you also receive an email with the results? Looking at the logs I guess maybe you didn't, as the filenames inside the zip file didn't match the expected filenames so it didn't extract the fasta/gbk files to send to the user.

I have uploaded a wrong .zip file and a correct one for testing. For the correct one I also received an email. However, the fasta/ gbk files were not attached to it.

> Sure - in this case should it should always use the first running option from the list?

Yes.

> I used 8080 for no reason except that it wasn't blocked by the uni firewall, while the default 5000 was for some reason.

Alright. I will discuss this tomorrow with the cluster IT & DKFZ IT. If they are not willing to unblock certain ports your mentioned solutions may be of interest. I will update this tomorrow.

**Comment by lkeegan** [comment]
@LArnoldt I'm realising I haven't documented this, but here is the current logic when a result zipfile is uploaded:

- parse the primary key `YY_MM_NN` from zip filename assuming form `YY_MM_NN_....zip`
  - return error message if corresponding sample not found (this happened for your first zip upload)
- store this zipfile as the zip results for this sample
  - a "zip" link is added to the results table allowing the user to download this file
- try to extract the file `YY_MM_NN_samplename.fasta` from the zipfile
  - here `samplename` is the sample name the user entered when submitting the sample
  - if this file is found a "fasta" link will be added to the results table to download this file
- do the same for `YY_MM_NN_samplename.gbk`
- send user an email
  - attach the fasta and gbk files if present
  - (for your second zip upload the filenames inside the zipfile didn't match so these files didn't get extracted)

Is this what you would like? Two potentially more consistent options could be:

- more strict validation
  - also return an error message if fasta/gbk files with these expected names are not found inside zip file
- less strict validation
  - ignore the names of the files in zipfile and just assume they are correct and extract them / send them to the user

**Comment by LArnoldt** [comment]
> I used 8080 for no reason except that it wasn't blocked by the uni firewall, while the default 5000 was for some reason.

Yesterday it seemed to work with port 443 (This should be available on the DKFZ network & cluster.). However, currently I am receiving JSON Decode Error -> No information is transmitted via the API. I guess you are currently modifying the backend of the site?

**Comment by lkeegan** [comment]
I'm not currently modifying it - the website is served on port 443 and the REST API is on port 8080 (so trying to use the REST API on port 443 won't work)

But if port 443 is available everywhere then I'll look at implementing #40 to allow the API to also use this port

**Comment by LArnoldt** [comment]
This would be very valuable I guess since every port except 25 and 443 is blocked in DKFZ Networks.

**Comment by lkeegan** [comment]
@LArnoldt you should now be able to access the REST API using the https url
- `https://circuitseq.iwr.uni-heidelberg.de/api`

(See updated [notebooks/api_examples.ipynb](https://github.com/ssciwr/circuit_seq/blob/main/notebooks/api_examples.ipynb))
