### ISSUE TITLE
All 96 slots taken for this week

### ISSUE THREAD

**Issue by LArnoldt** [ssciwr/circuit_seq#48]
Possibly I just missed that, but when I went through the slides from the first meeting I stumbled over this sentence:

"Would also need a case for when all 96 slots are taken for a week how best to handle this case?"

Is this already taken into consideration? I would probably just close the input form, when the maximum number is reached & people could show their interest anyway per e-mail, so we can become aware if too limitied avilability is a problem?

**Comment by EdGreen21** [comment]
I think the manual input means that it's unlikely users will have the patience to fill in 96 samples... then again some PhDs will do anything if it's free, so I'd agree having a webpage saying 'full for this week, email e.green@dkfz.de if urgent request'.

This raises a question for future development: do we want to support users uploading multiple files at once, or leave this for future?  My feeling is we should focus on the analysis development for now, and punt this into a 'nice to have' future feature. FYI commercial providers ask users how many samples they want to submit, then dynamically change the website to add additional rows to the table (all of which would need their own reference selection box). 

 This would likely require significant changes to how the sample submission page is coded, for minimal benefit

**Comment by lkeegan** [comment]
Currently if all the slots are taken then clicking submit sample on the website does nothing - I'll change this to hide the submit sample form if there are no samples left and instead display this text:
- 'full for this week, email [e.green@dkfz.de](mailto:e.green@dkfz.de) if urgent request'

I'll keep the multiple file uploads option in mind for the future, should be fairly straightforward to add this when it becomes relevant.
