### ISSUE TITLE
Make "Sample Table" output compatible with circuitSEQ input

### ISSUE THREAD

**Issue by EdGreen21** [ssciwr/circuit_seq#5]
This is an ongoing aim, and will require input from Lucas Arnoldt

**Comment by LArnoldt** [comment]
Essentially we will need to be able to export the admin table to a .tsv file. Also, we do need the website to proivde us with a .zip file or similar with the reference fasta files.

**Comment by lkeegan** [comment]
@LArnoldt I added a link to download a zip file of the samples table as tsv and any reference sequences - feel free to re-open this issue if you have any problems or comments on this.

**Comment by LArnoldt** [comment]
Wonderful. Thank you!
