### ISSUE TITLE
long-lived JWT token for API access

### ISSUE THREAD

**Issue by lkeegan** [ssciwr/circuit_seq#55]
- currently all tokens are invalidated on server restart when we re-generate the random number used to seed generation/validation
- this is simple and good for security as a stolen key doesn't stay valid for very long
- it's also not too inconvenient for the web interface as a new token is generated with each login
- but for API users this is inconvenient as they have to frequently regenerate their API key

The simplest solution:

- fix the seed
- give out short-lived (e.g 30min) tokens for the web interface
- give out a long-lived (e.g. 1 year) on the admin API
- if an admin API token is compromised, change the seed which invalidates all existing tokens

More complicated solutions:

- keep a database of revoked tokens

**Comment by LArnoldt** [comment]
I think a 1 year admin API key is more than enough. Could also be shorther time period. FOr users on the web interface I guess it doesn't really matter.
