### ISSUE TITLE
dna reference sequence `<unknown id>`

### ISSUE THREAD

**Issue by lkeegan** [ssciwr/circuit_seq#73]
@EdGreen21 I see you uploaded a dna file to the website which again ended up with `<unknown id>` as the description - would you be able to send me this file (or attach here) so I can try to fix this?

Also would it make sense to use the original filename as a fallback if neither of the sequence parsing libraries find an id or description?

**Comment by EdGreen21** [comment]
Most Snapgene files do not seem to use the <id> field, so fallback to filename would be ideal. 

Attached are a number of files in various versions of snapgene *.dna format, as well as a linear DNA sequence that a user might submit if they only knew part of the sequence or - worst case - screwed up and didn't properly annotate their plasmids. @LArnoldt let's see how this affects the analysis
[Example DNA files.zip](https://github.com/ssciwr/circuit_seq/files/10195048/Example.DNA.files.zip)

**Comment by EdGreen21** [comment]
nice solution!
