### ISSUE TITLE
Sample submission workflow

### ISSUE THREAD

**Issue by LArnoldt** [ssciwr/circuit_seq#78]
The website currently gives no details about the sample submission workflow.

Would be good to add some information on the main page. sth. like this:

```
The CircuitSEQ project is a trial service offering sequencing of DNA samples.

- Samples must be submitted by Wednesday each week via a letter box at H2.06.053.
- Samples must be submitted in eppendorf 1.5 mlmicrotubes.
- Samples must have a concentration between 143 ng/μl (At least 7 μl sample) and 1000 ng/μl (At least 1 μl sample).
- Results will be available on Friday.
- Remaining available samples this week: 0.
```

Since we require the poeple to provide us with samples in the right concentration anyway it would be good if users would need to add the concentration in the sample submission process & the sample concentration could get part of the reference sheet.

@lkeegan @edgreen21

**Comment by LArnoldt** [comment]
Not sure, whether this got broken by replacing the text: 

- Remaining available samples this week: 0. -> Still shows 0 for this week, however it should show 95 samples available?

**Comment by lkeegan** [comment]
Looks like this is working normally currently - but the website displaying 0 would happen if the frontend is running but the backend is not.
Maybe a transient issue when the backend was being updated/restarted? But let me know if it happens again.
