### ISSUE TITLE
Add feedback option "Sample did not work"

### ISSUE THREAD

**Issue by LArnoldt** [ssciwr/circuit_seq#82]
Sometimes, we do not reach a result for a sample, as the concentration is too low or faulty handling by us. Instead of uploading a .zip file it would be great if we could trigger a feedback email via the admin panel/ the API saying.

```
Dear l.arnoldt@dkfz-heidelberg.de,

Your sample 22_50_A1_pCW57_1 has been processed. However, no correct de-novo assembly has been determined. Please consider handing in this sample next week again.

Best wishes,

CircuitSEQ Team.
```

**Comment by lkeegan** [comment]
We could add two more parameters to the `/admin/result` endpoint:

- primary_key (string)
- success (boolean)
- file (same as before)

To upload a results file you would set the `primary_key`, `success=True`, and the file as before

To send a message that there are no results you would set the `primary_key` and `success=False`

Would that work?

It could also do a consistency check between the zip filename and the primary_key (see also #84) before accepting the result.

**Comment by lkeegan** [comment]
@LArnoldt this is now implemented, see https://github.com/ssciwr/circuit_seq/blob/main/notebooks/api_examples.ipynb for examples of uploading analysis success and analysis failure. You can also do this manually from the admin page on the website.

Here is an example email for `success="false"`:

```
Dear liam.keegan@iwr.uni-heidelberg.de,

Your sample 23_16_A1_asdsds has been processed, however no correct de-novo assembly has been determined.

Please consider handing in this sample next week again.

Best wishes,

CircuitSEQ Team.
https://circuitseq.iwr.uni-heidelberg.de
```

And here an example email for `success="true"` with fasta/gbk files attached (unchanged by this PR):

```
Dear liam.keegan@iwr.uni-heidelberg.de,

Your sample 23_16_A1_asdsds has been processed and the results are attached to this email.

You can also download the full analysis data by logging in to your account at https://circuitseq.iwr.uni-heidelberg.de

Best wishes,

CircuitSEQ Team.
https://circuitseq.iwr.uni-heidelberg.de
```
