### ISSUE TITLE
result upload validation

### ISSUE THREAD

**Issue by lkeegan** [ssciwr/circuit_seq#84]
Current validation logic of result zipfile upload:

- parse the primary key `YY_MM_NN` from zip filename assuming form `YY_MM_NN_....zip`
  - return error message if corresponding sample not found (this happened for your first zip upload)
- store this zipfile as the zip results for this sample
  - a "zip" link is added to the results table allowing the user to download this file
- try to extract the file `YY_MM_NN_samplename.fasta` from the zipfile
  - here `samplename` is the sample name the user entered when submitting the sample
  - if this file is found a "fasta" link will be added to the results table to download this file
- do the same for `YY_MM_NN_samplename.gbk`
- send user an email
  - attach the fasta and gbk files if present
  - (for your second zip upload the filenames inside the zipfile didn't match so these files didn't get extracted)

Is this what you would like? Two potentially more consistent options could be:

- more strict validation
  - also return an error message if fasta/gbk files with these expected names are not found inside zip file
- less strict validation
  - ignore the names of the files in zipfile and just assume they are correct and extract them / send them to the user

(copied from https://github.com/ssciwr/circuit_seq/issues/43#issuecomment-1347932932_)

**Comment by EdGreen21** [comment]
looks like great progress since I last checked in!
